services:
  web:
    image: contextfree-web
    build: .
    container_name: contextfree-web
    ports:
      - 3000:3000
    environment:
      - DEV=1
    volumes:
      - ./public:/app/public:ro
      - ./src:/app/src:ro

