name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: git clone --depth=1 -b wasm https://github.com/azizghuloum/context-free.git
    - run: (cd context-free && docker build . -t contextfree -f Wasm.Dockerfile)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag context-free-web
    - run: (container=$(docker create context-free-web) && docker cp ${container}:/cfdg/build ./build)
    - run: ls && ls build
